### ISSUE TITLE
Unable to run oncall - throws ModuleNotFoundError

### ISSUE THREAD

**Issue by arjunnath** [linkedin/oncall#176]
Hi,

I followed the instructions given to install and run oncall but ran into this issue :
Note - python version is 3.6.3, using virtualenv , OS is linux SLES11.

`
(venv) $ make serve
oncall-dev ./configs/config.yaml
Traceback (most recent call last):
  File "/nfs/user1/workspace/oncall/venv/bin/oncall-dev", line 11, in <module>
    load_entry_point('oncall', 'console_scripts', 'oncall-dev')()
  File "/nfs/user1/workspace/oncall/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/nfs/user1/workspace/oncall/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/nfs/user1/workspace/oncall/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/nfs/user1/workspace/oncall/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/nfs/user1/workspace/oncall/src/oncall/bin/run_server.py", line 11, in <module>
    import oncall.utils
  File "/nfs/user1/workspace/oncall/src/oncall/utils.py", line 13, in <module>
    from constants import ONCALL_REMINDER
ModuleNotFoundError: No module named 'constants'
make: *** [serve] Error 1
`

I tried adding the local directory to the PATH variable, but receive the same error.
Can someone please advise ?

**Comment by houqp** [comment]
oncall only works for python2 right now.

**Comment by arjunnath** [comment]
> oncall only works for python2 right now.

I dont see this mentioned anywhere in the github documentation.
Are you sure the ModuleNotFoundError is due to python version ?

**Comment by dwang159** [comment]
Yes, this is due to a change in the `import` statement from python 2 to 3. See https://www.python.org/dev/peps/pep-0404/.

**Comment by arjunnath** [comment]
Ok Thanks. I was able to start oncall by switching to python2.
Closing this issue.
