### ISSUE TITLE
Getting error while installing oncall (pip install -e '.[dev]')

### ISSUE THREAD

**Issue by gani-murugesan** [linkedin/oncall#203]
Hi Team,

We are trying oncall in our infrastructure,  I am getting the below error while installing "pip install -e '.[dev]'". Please help to fix it.

(oncall) root@iris2:~/oncall# python --version
Python 2.7.6

(oncall) root@iris2:~/oncall# pip --version
pip 18.0 from /root/oncall/local/lib/python2.7/site-packages/pip (python 2.7)

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ptgnVW/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).

**Comment by srikanth11** [comment]
Please use this below command 
pip install -e .[dev]
