### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by salk31** [linkedin/oncall#242]
I'm getting the following error:
```
Fri Mar 15 18:22:55 2019 - [uwsgi-daemons] respawning "/home/oncall/env/bin/oncall-scheduler /home/oncall/config/config.yaml" (uid: 1000 gid: 1000)
Traceback (most recent call last):
  File "/home/oncall/env/bin/oncall-scheduler", line 6, in <module>
    from oncall.bin.scheduler import main
  File "/home/oncall/env/local/lib/python2.7/site-packages/oncall/bin/scheduler.py", line 13, in <module>
    from oncall.api.v0.schedules import get_schedules
  File "/home/oncall/env/local/lib/python2.7/site-packages/oncall/api/v0/schedules.py", line 4, in <module>
    from urllib.parse import unquote
ImportError: No module named parse

```
I think I'm using the latest version of oncall git id `a4829c0e93ec40cf1886f583ded2bd9c59752f5b`

Docker version 18.09.3
Packer version v1.3.5

I've been trying to follow the get started on https://oncall.tools/docs/admin_guide.html (except for typo about oncall.json path?).

I'm new to docker and python so sorry if I'm missing something obvious.

Cheers

Sam

**Comment by salk31** [comment]
I checked out b688b3c88551d3f0379dd13748ea066f91d890a2  a few commits back before the python 3 changes and it seems OK now.
