### ISSUE TITLE
OperationalError: (pymysql.err.OperationalError) when running oncall

### ISSUE THREAD

**Issue by mhyousefi** [linkedin/oncall#273]
When running the app using `oncall-dev ./configs/config.yaml`, I get the following stack trace.
```
<PROJECT_DIR>/oncall/src/oncall/utils.py:33: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(config_file)
[2019-10-12 16:50:33 +0330] [31111] [INFO] Starting gunicorn 19.9.0
[2019-10-12 16:50:33 +0330] [31111] [INFO] Listening at: http://0.0.0.0:8080 (31111)
[2019-10-12 16:50:33 +0330] [31111] [INFO] Using worker: gevent
[2019-10-12 16:50:33 +0330] [31116] [INFO] Booting worker with pid: 31116
[2019-10-12 16:50:33 +0330] [31117] [INFO] Booting worker with pid: 31117
[2019-10-12 16:50:33 +0330] [31119] [INFO] Booting worker with pid: 31119
[2019-10-12 16:50:33 +0330] [31120] [INFO] Booting worker with pid: 31120
[2019-10-12 16:50:33 +0330] [31121] [INFO] Booting worker with pid: 31121
[2019-10-12 16:50:33 +0330] [31122] [INFO] Booting worker with pid: 31122
[2019-10-12 16:50:33 +0330] [31123] [INFO] Booting worker with pid: 31123
INFO:oncall.auth:Auth debug turned on.
INFO:oncall.auth:Auth debug turned on.
[2019-10-12 16:50:33 +0330] [31117] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "<ENV_DIR>/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "<ENV_DIR>/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "<ENV_DIR>/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "<ENV_DIR>/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "<ENV_DIR>/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "<PROJECT_DIR>/oncall/src/oncall/bin/run_server.py", line 32, in load
    app = oncall.app.get_wsgi_app()
  File "<PROJECT_DIR>/oncall/src/oncall/app.py", line 162, in get_wsgi_app
    init(utils.read_config(sys.argv[1]))
  File "<PROJECT_DIR>/oncall/src/oncall/app.py", line 142, in init
    init_falcon_api(config)
  File "<PROJECT_DIR>/oncall/src/oncall/app.py", line 82, in init_falcon_api
    init_auth(application, config['auth'])
  File "<PROJECT_DIR>/oncall/src/oncall/auth/__init__.py", line 250, in init
    connection = db.connect()
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/engine/base.py", line 2306, in raw_connection
    self.pool.unique_connection, _connection
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "build/bdist.macosx-10.14-intel/egg/sqlalchemy/engine/default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "<ENV_DIR>/lib/python2.7/site-packages/PyMySQL-0.9.3-py2.7.egg/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "<ENV_DIR>/lib/python2.7/site-packages/PyMySQL-0.9.3-py2.7.egg/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "<ENV_DIR>/lib/python2.7/site-packages/PyMySQL-0.9.3-py2.7.egg/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'oncall-mysql' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: http://sqlalche.me/e/e3q8)
[2019-10-12 16:50:33 +0330] [31117] [INFO] Worker exiting (pid: 31117)
[2019-10-12 16:50:33 +0330] [31116] [ERROR] Exception in worker process
```
Now, in `configs/config.yaml`, I have changed the password field to my own password. Can you help me with this? Here's how it looks like:
```
server:
  host: 0.0.0.0
  port: 8080
oncall_host: http://localhost:8080
metrics: dummy
db:
  conn:
    kwargs:
      scheme: mysql+pymysql
      user: root
      password: "MY_PASSWORD"
      host: oncall-mysql
      port: 3306
      database: oncall
      charset: utf8
      echo: True
    str: "%(scheme)s://%(user)s:%(password)s@%(host)s:%(port)s/%(database)s?charset=%(charset)s"
  kwargs:
    pool_recycle: 3600
healthcheck_path: /tmp/status
```

**Comment by markckimball** [comment]
db.conn.kwargs.host property should be the hostname of the system your mysql server is running on.

For example the host should be changed to localhost if your are running mysql locally:


```db:
  conn:
    kwargs:
      scheme: mysql+pymysql
      user: root
      password: "MY_PASSWORD"
      host: localhost
      port: 3306
      database: oncall
      charset: utf8
      echo: True
```

**Comment by reach-the-sky** [comment]
Even if the hostname matches it is not working
My SQL docker compose
```
version: "3.4"

services:
  mysqlservice:
    hostname: mysqlservice
    container_name: mysqlcontainer
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - "achieve"
    volumes:
      - type: bind
        source: ./mysql-bind
        target: /var/lib/mysql
      - type: bind
        source: ./mysql-conf
        target: /etc/mysql/conf.d

networks:
  achieve:
    external: true
```

This is my oncall config:
```
server:
  host: 0.0.0.0
  port: 8080
oncall_host: http://localhost:8080
metrics: dummy
db:
  conn:
    kwargs:
      scheme: mysql+pymysql
      user: oncalluser
      password: "oncalluser"
      host: mysqlservice
      port: 3306
      database: oncall
      charset: utf8
      echo: True
    str: "%(scheme)s://%(user)s:%(password)s@%(host)s:%(port)s/%(database)s?charset=%(charset)s"
  kwargs:
    pool_recycle: 3600
healthcheck_path: /tmp/status
```


Error:
```
[2022-11-04 11:32:55 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/oncall/src/oncall/app.py", line 118, in __call__
    return self.app(env, start_response)
  File "/usr/local/lib/python3.8/dist-packages/Beaker-1.11.0-py3.8.egg/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/local/lib/python3.8/dist-packages/falcon-1.4.1-py3.8.egg/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/opt/oncall/src/oncall/auth/login.py", line 26, in on_post
    connection = db.connect()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/engine/base.py", line 3234, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 397, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 1193, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 660, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/impl.py", line 169, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 338, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 623, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 843, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 838, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/engine/create.py", line 640, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/engine/default.py", line 576, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/PyMySQL-1.0.2-py3.8.egg/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/PyMySQL-1.0.2-py3.8.egg/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/socket.py", line 83, in create_connection
    addrs = list(getaddrinfo(host, port, 0, SOCK_STREAM))
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
127.0.0.1 - - [04/Nov/2022:11:32:55 +0000] "POST /login HTTP/1.1" 500 0 "-" "-"
```
