### ISSUE TITLE
Docker build fails - No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by prestonvanloon** [linkedin/oncall#300]
```
Step 8/17 : RUN chown -R oncall:oncall /home/oncall/source /var/log/nginx /var/lib/nginx     && sudo -Hu oncall mkdir -p /home/oncall/var/log/uwsgi /home/oncall/var/log/nginx /home/oncall/v
ar/run /home/oncall/var/relay     && sudo -Hu oncall python3 -m venv /home/oncall/env     && sudo -Hu oncall /bin/bash -c 'source /home/oncall/env/bin/activate && cd /home/oncall/source &&
pip install .'
 ---> Running in 7d8f5f8d9231
Processing /home/oncall/source
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-6ug_9913-build/setup.py", line 10, in <module>
        with open('README.md', 'r') as fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

```

**Comment by lyveng** [comment]
I think it is because of this [specific commit](https://github.com/linkedin/oncall/commit/88809d7911193bf4c5c53e9145870c718ca7de28) where in setup.py they are opening README.md file to populate the long_description field. But this file doesn't seem to be present in /home/oncall/source while running `pip install .` in the Dockerfile. Adding this line `COPY README.md /home/oncall/source/README.md` fixed the issue for me.
