### ISSUE TITLE
make build fails on MarkupSafe

### ISSUE THREAD

**Issue by glassrye** [linkedin/oncall#369]
Running **docker build** against the Dockerfile results in the same output.

```
#13 14.76 Collecting MarkupSafe>=2.0 (from jinja2->oncall==1.4.3)
#13 14.83   Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz
#13 14.93     Complete output from command python setup.py egg_info:
#13 14.93     Traceback (most recent call last):
#13 14.93       File "<string>", line 1, in <module>
#13 14.93       File "/tmp/pip-build-ci8_gs00/MarkupSafe/setup.py", line 61, in <module>
#13 14.93         run_setup(True)
#13 14.93       File "/tmp/pip-build-ci8_gs00/MarkupSafe/setup.py", line 44, in run_setup
#13 14.93         ext_modules=ext_modules if with_binary else [],
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
#13 14.93         return distutils.core.setup(**attrs)
#13 14.93       File "/usr/lib/python3.6/distutils/core.py", line 121, in setup
#13 14.93         dist.parse_config_files()
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/dist.py", line 494, in parse_config_files
#13 14.93         ignore_option_errors=ignore_option_errors)
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/config.py", line 106, in parse_configuration
#13 14.93         meta.parse()
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/config.py", line 382, in parse
#13 14.93         section_parser_method(section_options)
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/config.py", line 355, in parse_section
#13 14.93         self[name] = value
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/config.py", line 173, in __setitem__
#13 14.93         value = parser(value)
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/config.py", line 430, in _parse_version
#13 14.93         version = self._parse_attr(value)
#13 14.93       File "/home/oncall/env/lib/python3.6/site-packages/setuptools/config.py", line 305, in _parse_attr
#13 14.93         module = import_module(module_name)
#13 14.93       File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
#13 14.93         return _bootstrap._gcd_import(name[level:], package, level)
#13 14.93       File "<frozen importlib._bootstrap>", line 994, in _gcd_import
#13 14.93       File "<frozen importlib._bootstrap>", line 971, in _find_and_load
#13 14.93       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
#13 14.93     ModuleNotFoundError: No module named 'markupsafe'
#13 14.93
#13 14.93     ----------------------------------------
#13 15.04 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ci8_gs00/MarkupSafe/
```

**Comment by glassrye** [comment]
Setting `'markupsafe==1.1.1'` in `setup.py` seems to have solved the build issue.

**Comment by glassrye** [comment]
The better thing to do was set `FROM ubuntu/20.04` and add `ENV DEBIAN_FRONTEND=noninteractive ` in the Dockerfile and let MarkupSafe be `>= 2.0.0`

**Comment by diegocepedaw** [comment]
@glassrye, can you open a PR for the change. We don't use Docker and due to other projects haven't really had any time to dedicate to maintaining the docker functionality updated. We always welcome those who do use it to make PRs to keep it update it, fix issues, or add features.

**Comment by ChrisCarini** [comment]
@diegocepedaw @roock - I noticed this still appears to be happening with the latest commit (3a4c43f05cf029527ca25b899a35b39afce58312). Pinning `markupsafe` to `2.0.1` appears to do the trick for me. I'll submit a PR for this shortly.
