### ISSUE TITLE
DB Connect Error with docker hostname

### ISSUE THREAD

**Issue by reach-the-sky** [linkedin/oncall#384]
Even if the hostname matches it is not working
(With the same setup iris and oncall-admin are working fine)
My SQL docker compose
```
version: "3.4"

services:
  mysqlservice:
    hostname: mysqlservice
    container_name: mysqlcontainer
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - "achieve"
    volumes:
      - type: bind
        source: ./mysql-bind
        target: /var/lib/mysql
      - type: bind
        source: ./mysql-conf
        target: /etc/mysql/conf.d

networks:
  achieve:
    external: true
```

This is my oncall config:
```
server:
  host: 0.0.0.0
  port: 8080
oncall_host: http://localhost:8080
metrics: dummy
db:
  conn:
    kwargs:
      scheme: mysql+pymysql
      user: oncalluser
      password: "oncalluser"
      host: mysqlservice
      port: 3306
      database: oncall
      charset: utf8
      echo: True
    str: "%(scheme)s://%(user)s:%(password)s@%(host)s:%(port)s/%(database)s?charset=%(charset)s"
  kwargs:
    pool_recycle: 3600
healthcheck_path: /tmp/status
```

Error:
```
[2022-11-04 11:32:55 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/oncall/src/oncall/app.py", line 118, in __call__
    return self.app(env, start_response)
  File "/usr/local/lib/python3.8/dist-packages/Beaker-1.11.0-py3.8.egg/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/local/lib/python3.8/dist-packages/falcon-1.4.1-py3.8.egg/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/opt/oncall/src/oncall/auth/login.py", line 26, in on_post
    connection = db.connect()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/engine/base.py", line 3234, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 397, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 1193, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 660, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/impl.py", line 169, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 338, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 623, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 843, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/pool/base.py", line 838, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/engine/create.py", line 640, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/SQLAlchemy-2.0.0b2-py3.8.egg/sqlalchemy/engine/default.py", line 576, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/PyMySQL-1.0.2-py3.8.egg/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/PyMySQL-1.0.2-py3.8.egg/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/socket.py", line 83, in create_connection
    addrs = list(getaddrinfo(host, port, 0, SOCK_STREAM))
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_socketcommon.py", line 212, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/resolver/thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/usr/local/lib/python3.8/dist-packages/gevent-1.4.0-py3.8-linux-x86_64.egg/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
127.0.0.1 - - [04/Nov/2022:11:32:55 +0000] "POST /login HTTP/1.1" 500 0 "-" "-"
```

**Comment by reach-the-sky** [comment]
Sorry for the inconvenience, I forgot to update the oncall docker-compose. Closing the issue.
